apiVersion: batch/v1
kind: Job
metadata: 
  name: sample-job
spec:
  template:
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["echo", "hello from kubernets job"]
      restartpolicy: Never      