apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels: 
    app: demo
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports: 
        - containerPort: 80
    - name: busybox-container
      image: busybox
      command: ["sleep", "3600"]
          