apiVersion: batch/v1
kind: Job
metadata: 
  name: multi-container-job
spec:
  template:
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["echo", "hello from busybox"]
        - name: alpine
          image: alpine
          command: ["echo", "hello from alpine"]
      restartpolicy: Never    
      